zerodytrash/Simple-YouTube-Age-Restriction-Bypass

- Simple-YouTube-Age-Restriction-Bypass.user.js
I don't really understand why but when logged in my account, videos have a special "UNPLAYABLE" status. Simply adding it to the unlockablePlayerStates fixed it and allowed me to watch every age restricted videos.
> Added "UNPLAYABLE" unlockablePlayerState that fixes bypass on my account

- account-proxy/innertube-api.js
Based off https://github.com/yt-dlp/yt-dlp/commit/2fd226f6a76715e429709d7172183d48e07c7ab3
This should fix controversial videos returning CONTENT_CHECK_REQUIRED via the proxy, specifically age-gated ones like https://www.youtube.com/watch?v=nGC3D_FkCmg
> Fix controversial age-gated videos

- Simple-YouTube-Age-Restriction-Bypass.user.js
e.g. https://www.youtube.com/watch?v=HsUATh_Nc2U where the copyrighted music causes the embed to only work when on a public domain
Based off https://stackoverflow.com/a/59640711
> Catch age-gated videos with music embed restrictions for /player bypass

- Simple-YouTube-Age-Restriction-Bypass.user.js
Based off reports from korean users on yt-dlp's discord.
P.S. Since the statuses also changes a bit based on region, I think we should detect age-gating via the `desktopLegacyAgeGateReason` property instead (which seems more reliable despite it's name)
> More age gate playability statuses

- Simple-YouTube-Age-Restriction-Bypass.user.js
By throwing the `Error` object which includes stack trace.
> Improve throwing error

- Simple-YouTube-Age-Restriction-Bypass.user.js
> Restore watch next recommendations for age-gated videos

- LICENSE
Since the userscript license is set to MIT, it would be logical to add the same license to the repo.
License was entirely auto-generated by GitHub.
> chore: Add MIT license

- babel.config.js
This has a side-effect of adding some whitespaces/newlines in the output
> Fix misplaced comments by Babel

- .gitattributes
- .github/workflows/build.yml
- .prettierrc.cjs
- package.json
- src/components/innertubeClient.js
- src/components/interceptor.js
- src/components/toast/index.js
- src/components/unlocker.js
- src/main.js
- src/utils/index.js
CI currently only checks if the code is correctly formatted, or else it fails with a clear message and the PR owner has to run `npm run format`. This CI runs on each push and pull request, additionally it can be ran manually by the repo owner.
Additional changes:
- Formatted files
- Removed `trailingComma: "none"` from Prettier config
- Added `eol=lf` to `.gitattributes` to force eol formats
> [chore] add CI & make some additional changes

- src/components/interceptor.js
This allows other userscripts to interoperate with this one, or any other for that matter.
A particular property that would benefit from this decorating is "playerResponse", which contains loads of knobs that can be turned by other userscripts as well.
An example I have for how another userscript could do its work with this is like so:
```js
// Interop with "Simple YouTube Age Restriction Bypass"
const {
get: getter,
set: setter,
} = Object.getOwnPropertyDescriptor(Object.prototype, "playerResponse") ?? {
set(value) {
this[Symbol.for("YTBetter")] = value;
},
get() {
return this[Symbol.for("YTBetter")];
},
};
const isObject = (value) => value != null && typeof value === "object";
Object.defineProperty(Object.prototype, "playerResponse", {
set(value) {
if (isObject(value)) {
const { …
```
> Decorate `interceptObject`'s target

- src/components/unlocker/next.js
Proxy returns `attributedDescription` instead of `description`.
"Improvise, adapt to the environment, Darwin, I Ching, whatever man, we gotta roll with it."
**Related issues**
- #159
> [fix] description not being set

- .prettierrc.cjs
- dprint.json
- package-lock.json
- package.json
- src/components/confirmation.js
- src/components/endpoints/innertube.js
- src/components/endpoints/proxy.js
- src/components/errorScreen/index.js
- src/components/inspectors/index.js
- src/components/inspectors/player.js
- src/components/inspectors/search.js
- src/components/interceptors/generic.js
- src/components/interceptors/json.js
- src/components/interceptors/xhrOpen.js
- src/components/requestPreprocessor.js
- src/components/strategies/index.js
- src/components/strategies/next.js
- src/components/strategies/player.js
- src/components/thumbnailFix.js
- src/components/toast/index.js
- src/components/unlocker/index.js
- src/components/unlocker/next.js
- src/components/unlocker/player.js
- src/config.js
- src/extension/main.js
- src/extension/multi-page-menu.js
- src/main.js
- src/utils/index.js
- src/utils/logger.js
dprint (written in Rust) is much faster than Prettier by a long shot. Formatting the `user.js` in `dist` took ~\~400ms~ ~700ms with Prettier, now this only takes ~20ms.
I also find the formatting much better with dprint. It reorders all the imports unlike Prettier and some of the multi-line code is more readable.
Out of the box it formats TypeScript. Could come in handy if we decide to transition from JavaScript in the future.
This change will impact building, formatting and GitHub CI.
> [chore] replace Prettier with dprint

- src/extension/main.js
The current injection method has an issue on Firefox where globals are not defined as they should be, leading to issues where `window.` has to be prefixed on all native functions, objects, etc.
Now injector stage 1 injects stage 2, which in turn injects the main script.
Stage 1: `onclick` event
Stage 2: `script` tag
~Hopefully this is just as fast as not to cause any race conditions.~
**EDIT:** Performance should be the same, maybe slightly better in FF. Stage 2 runs immediately after stage 1 (it's blocking).
**Related issues**
- #172
> [extension] use two stages of injection

- .github/scripts/publish_greasyfork.sh
- .github/workflows/release_and_publish.yml
This PR introduces a new workflow for releasing and publishing on GitHub and GreasyFork. The workflow is triggered whenever a new GitHub release is published.
**Automation Overview**
This workflow automates the process of changing the package.json version number to match the release tag. It then builds and commits the latest release and automatically uploads the latest assets along with the GitHub release. Finally, the updated script is published on GreasyFork.
> [chore] Add automated release pipeline

- src/components/unlocker/player.js
Related: 
- #191
YouTube checks if the `trackingParams` in the response matches the decoded `trackingParam` in `responseContext.mainAppWebResponseContext`. However, the "TV Embedded Player" client does not include the `trackingParam` in the `responseContext`, causing the check to fail.
This workaround addresses the issue by hardcoding the `trackingParam` in the "TV Embedded Player" context.
> [fix] "Something went wrong" error for videos

- src/config.js
Resolved / Related Issues
- #202
> [fix] replace outdated video proxy url

- src/components/unlocker/player.js
Resolved / Related Issues
- #205
Previous fix was applied to only one bypass, now this is applied globally
> [fix] `Something went wrong` error for videos - take 2

- src/components/unlocker/player.js
Account proxy response currently does not include `playerConfig`.
Until we rewrite the account proxy to only include the necessary and bare minimum response, this will be fixed in the client only. I don't want to take the risk of somehow breaking it as the current proxy codebase IMO is a mess.
> [fix] video `startTimeSecs` ignored with proxy

- src/components/interceptors/request.js
- src/components/interceptors/xhrOpen.js
- src/components/requestPreprocessor.js
- src/utils/index.js
Resolved / Related Issues
- #220 
Interceptors would try to handle `data:` url's
> [fix] interceptors exception

- README.md
Bromite is no longer maintained and therefore it shouldn't be advised to use it. Cromite is an updated fork which also supports userscripts.
> docs(readme): replace bromite with cromite
